name: finalproject
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  dropdown_button2: ^2.3.9
  smooth_page_indicator: ^1.1.0
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^2.0.9
  dotted_border: ^2.0.0
  file_picker: ^6.1.1
  percent_indicator: ^4.2.3
  pinput: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  google_sign_in: ^6.2.1
 
  
  
  

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
